version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "50051:50051"
    networks:
      - grpc_network

  client1:
    build: ./client1
    restart: unless-stopped
    networks:
      - grpc_network
  client2:
    build: ./client2
    restart: unless-stopped
    networks:
      - grpc_network
       
       
networks:
  grpc_network:
    driver: bridge